### PR TITLE
Add exp tanh to value

### PR DESCRIPTION
**Pull request by bradklingensmith**
You might already have these changes locally, but I figured I'd upload this just in case, since people that watched the YouTube video probably expect these functions to be implemented.

### CODE REVIEW

**Comment by karpathy** [comment]
Thank you for the PR. I'm kind of on a fence about adding it because it might be bloating micrograd a little bit. The point is not to have an all-encompassing library. Agree that people might expect it though based on the video... HMM

**Comment by bradklingensmith** [comment]
Then I recommend omitting tanh() and adding just exp(). exp() is so widely used that it's almost essential to a machine learning library. Also, you showed 2 versions of tanh() in the video, so people will be less surprised not to find the first version.

Does that reasonable? If so, I'll update and re-upload.

**Comment by bradklingensmith** [comment]
Closing this to keep micrograd from becoming minigrad.

Btw, my personal use for exp and tanh was implementing [min-char-rnn with micrograd as the backend](https://github.com/bradklingensmith/micrograd). I thought you might find that amusing :)

**Comment by karpathy** [comment]
:) highly amusing. Can be done!

**Pull request closed without merging**
