### PR TITLE
Actually use h variable in example

### PR DESCRIPTION
**Pull request by bpesquet**
Thanks for this inspiring work!

### CODE REVIEW

**Comment by karpathy** [comment]
Ah yes good catch, i had fixed this in `test/` but not in readme. I'll probably improve this example a bit and also show off `.relu()` in addition. Thank you for the fix!

**Comment by bpesquet** [comment]
You're welcome.

Out of curiosity, what are your plans for this project? I imagine you want to keep it lean and clean, and you probably don't have much time to devote to it.

As a teacher, I find it immensely useful for explaining how AD is used by modern DL frameworks. I've [merged your code](https://github.com/bpesquet/pyfit/blob/master/pyfit/engine.py) into my own modest attempt at a minimalist ML library. I also added a few things, like type annotations and support for `-` and `/` operators.

Should you be interested, I could retrofit these changes into my fork and contribute them back to your repo. Anyway, thanks again for sharing this nice work ;)

**Comment by karpathy** [comment]
I'm so happy to hear you found this helpful in your teaching, pyfit looks awesome! And I agree and strongly believe that the best course for neural nets is basically the one that gets you to implement something like pyfit completely from scratch. I struggle to see how you could beat that. As for pyfit:

- I like the code structure / layout, it's very natural
- I have not yet graduated to type annotations because I find it clutters the code visually. I feel more internal pain from inability to parse code because it's visually overwhelming than from struggling to figure out what type different variables are, esp in a smaller code base like this.
- I like the use of **black** in principle, but in practice I'm very opinionated on the visual look and feel of my code and its overall aesthetic. I have come up with ways to encode additional semantic information into my code layout that I'm fond of, and I fear a formatter would destroy this degree of freedom.

Anyway, I'm rambling. To answer your questions I do plan to extend the library a tiny bit, but I'm probably opinionated enough that I'll do it more slowly and slightly differently. Your code will be a great reference though I imagine. Thank you!!

**Comment by karpathy** [comment]
Also really like all the supporting tissue you have around pyfit with badges, setuptools, requirements.txt etc. I'm very jealous that autograd is much more janky, I'll work to also make it look proper :)

**Pull request merged**
